# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('Description', models.TextField(blank=True, max_length=1200, verbose_name='Описание')),
                ('URL', models.CharField(blank=True, max_length=200, verbose_name='Web сайт')),
                ('Logo', models.ImageField(blank=True, upload_to='', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'заказчик',
                'db_table': 'customers',
                'verbose_name_plural': 'заказчики',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('Description', models.TextField(blank=True, max_length=1200, verbose_name='Описание')),
                ('Date', models.DateField(blank=True, verbose_name='Дата завершения')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customers', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'проект',
                'db_table': 'projects',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Sertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Title', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('Description', models.TextField(blank=True, max_length=1200, verbose_name='Описание')),
                ('File', models.FileField(blank=True, upload_to='sertificates/', verbose_name='Файл')),
                ('Active', models.BooleanField(verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'сертификат',
                'db_table': 'sertificates',
                'verbose_name_plural': 'сертификаты',
            },
        ),
        migrations.CreateModel(
            name='SertificateTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('Description', models.TextField(blank=True, max_length=1200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип сертификата',
                'db_table': 'sertificate_types',
                'verbose_name_plural': 'типы сертификатов',
            },
        ),
        migrations.AddField(
            model_name='sertificates',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SertificateTypes', verbose_name='Тип'),
        ),
    ]
